title: Oleksii Bidnyk
# logo: assets/img/cv_avatar_rounded.jpg
description: Portfolio 
show_download: true
# theme: jekyll-theme-minimal
remote_theme: minimal-mistakes-jekyll
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
